### PR TITLE
Use latest version of SnakeYAML

### PR DESCRIPTION
**Pull request by sebastianpoeplau**
Version 1.18 fixes a number of issues (see https://bitbucket.org/asomov/snakeyaml/wiki/Changes), including a problem with files that contain emojis.

### CODE REVIEW

**Comment by owainlewis** [comment]
Thanks

**Comment by sebastianpoeplau** [comment]
Would you mind releasing a new version so that we could use the update immediately? It would be much appreciated.

**Comment by owainlewis** [comment]
Done. 

```
[io.forward/yaml "1.0.6"]
```

**Comment by sebastianpoeplau** [comment]
Amazing, thank you!

**Pull request merged**
